# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cadee47102f14817c2cd1684a5a6d8232fc5fac8dcaa82f220f2e2376da7c88e2e17879389c809f8a8becff018467417f1f1e2b95707521e1b7164296d79c2a6

test:
  secret_key_base: 5c0b2ca48fa454dd40e60deffe4beccad35aeea05f1fde3c63de6b60b944b0191cc4bcb61dce9642c54ed6efde602832d22d7f3895d3be55f883368ba8c44370

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
